import * as Tabs from '@radix-ui/react-tabs';
import { ArrowLeft, CheckCircle2, ChevronDown, Clock3, FileCheck2, LockKeyhole, MoreHorizontal, Route, ShieldAlert, Thermometer } from 'lucide-react';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Area, CartesianGrid, ComposedChart, Line, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { usePrototype } from '../../app/PrototypeContext';
import { CHART_COLORS, ChartLegend, ChartTooltip } from '../../components/data-display/ChartSupport';
import { KeyValue } from '../../components/data-display/Panel';
import { Badge, Button, CheckState, EmptyState, Modal } from '../../components/ui/Primitives';
import { GovernanceIndicator, SeverityIndicator, WorkflowIndicator } from '../../components/ui/StatusIndicators';
import type { AuditEvent, GovernanceCheck, Incident } from '../../data/contracts';
import { useInvestigation } from '../../hooks/useControlTower';

type Decision = 'approve' | 'reject' | 'more-info';

export function Investigation() {
  const { incidentId = 'INC-2481' } = useParams();
  const { data, isLoading } = useInvestigation(incidentId);
  const { persona, displayMode, decisionVariant, notify, addAuditEvent, auditEvents, simulatedIncidents } = usePrototype();
  const navigate = useNavigate();
  const [decision, setDecision] = useState<Decision | null>(null);
  const [reason, setReason] = useState('');
  const [decided, setDecided] = useState<string | null>(null);
  const [expandedEvent, setExpandedEvent] = useState<string | null>(null);

  if (isLoading || !data) return <div className="page"><div className="skeleton skeleton-panel tall" /></div>;
  if (displayMode === 'disconnected') return <div className="page"><EmptyState title="Investigation unavailable" detail="The prototype data source is disconnected. No backend request was attempted." /></div>;
  const simulatedIncident = simulatedIncidents.find((item) => item.id === incidentId);
  const viewData = simulatedIncident ? { ...data, incident: simulatedIncident } : data;
  const { incident, recommendation } = viewData;
  const authorizationFailure = displayMode === 'permission-denied' || decisionVariant === 'authorization-failure';
  const canDecide = persona !== 'Read-only auditor' && !authorizationFailure;
  const expired = recommendation.validation === 'expired' || decisionVariant === 'expiry';

  const submitDecision = () => {
    if (!decision || (decision === 'reject' && reason.trim().length < 4)) return;
    const label = decisionVariant === 'conflict' ? 'Conflict — idempotent command already exists' : decisionVariant === 'uncertain-timeout' ? 'Outcome uncertain — automatic retry withheld' : decision === 'approve' ? 'Approved for simulated execution' : decision === 'reject' ? 'Recommendation rejected' : 'More information requested';
    setDecided(label);
    const event: AuditEvent = { id: `prototype-${decision}`, offsetMinutes: 0, actor: persona, type: 'Human decision recorded', summary: label, correlationId: 'corr-prototype-local', traceId: 'trace-prototype-local' };
    addAuditEvent(event); notify(`${label} · prototype only`); setDecision(null); setReason('');
  };

  return <div className="page investigation-page light-investigation">
    <button className="back-link" onClick={() => void navigate('/incidents')}><ArrowLeft size={16} />All incidents</button>
    <header className="investigation-context"><div className="incident-context-main"><div className="incident-labels"><span className="mono incident-id">{incident.id}</span><SeverityIndicator severity={incident.severity} /><WorkflowIndicator state={incident.state} /></div><h1>{incident.title}</h1><p><span className="mono">{incident.shipment}</span><span>{incident.product}</span></p></div><div className="incident-reviewer"><span>Reviewer</span><strong>{incident.reviewer ?? 'Unassigned'}</strong></div><button className="header-icon-button" aria-label="Incident actions"><MoreHorizontal size={19} /></button></header>
    <IncidentSummary incident={incident} evidenceComplete={recommendation.evidenceSufficient} />
    <div className="investigation-workspace">
      <main className="investigation-content">
        <TemperatureCard data={viewData} />
        <Tabs.Root defaultValue="overview" className="evidence-workspace"><Tabs.List className="evidence-tabs" aria-label="Investigation evidence views"><Tabs.Trigger value="overview">Overview</Tabs.Trigger><Tabs.Trigger value="sop">SOP Evidence</Tabs.Trigger><Tabs.Trigger value="recommendation">AI Recommendation</Tabs.Trigger><Tabs.Trigger value="governance">Governance</Tabs.Trigger><Tabs.Trigger value="audit">Audit Trail</Tabs.Trigger></Tabs.List>
          <Tabs.Content value="overview"><Overview incident={incident} /></Tabs.Content>
          <Tabs.Content value="sop"><SopEvidence evidence={viewData.evidence} /></Tabs.Content>
          <Tabs.Content value="recommendation"><RecommendationPanel recommendation={recommendation} /></Tabs.Content>
          <Tabs.Content value="governance"><GovernancePanel checks={viewData.governanceChecks} /></Tabs.Content>
          <Tabs.Content value="audit"><AuditTimeline events={[...viewData.audit, ...auditEvents]} expanded={expandedEvent} setExpanded={setExpandedEvent} /></Tabs.Content>
        </Tabs.Root>
      </main>
      <DecisionRail incident={incident} persona={persona} recommendation={recommendation} decided={decided} canDecide={canDecide} expired={expired} setDecision={setDecision} />
    </div>
    <Modal open={decision !== null} onOpenChange={(open) => !open && setDecision(null)} title={decision === 'approve' ? 'Confirm shipment hold' : decision === 'reject' ? 'Reject recommendation' : 'Request more information'} description="This decision is recorded in browser memory for design review only.">
      <div className="confirmation-summary"><KeyValue label="Action" value={decision === 'approve' ? 'HOLD SHIPMENT' : decision === 'reject' ? 'REJECT RECOMMENDATION' : 'REQUEST MORE INFORMATION'} /><KeyValue label="Shipment" value={incident.shipment} mono /><KeyValue label="Rationale" value={recommendation.rationale} /><div className="idempotency-note"><ShieldAlert size={18} /><span>Approval produces one idempotent simulated command. No external system is contacted.</span></div>{decision !== 'approve' && <label className="field-label">{decision === 'reject' ? 'Rejection reason (required)' : 'Information requested'}<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Enter a concise operational rationale…" /></label>}</div>
      <div className="dialog-actions"><Button variant="ghost" onClick={() => setDecision(null)}>Cancel</Button><Button variant={decision === 'reject' ? 'danger' : 'primary'} disabled={decision === 'reject' && reason.trim().length < 4} onClick={submitDecision}>Confirm prototype decision</Button></div>
    </Modal>
  </div>;
}

function IncidentSummary({ incident, evidenceComplete }: { incident: Incident; evidenceComplete: boolean }) { const values = [{ label: 'Current temperature', value: `${incident.temperature.toFixed(1)}°C`, critical: true }, { label: 'Allowed range', value: `${incident.allowedMin}–${incident.allowedMax}°C` }, { label: 'Breach duration', value: `${incident.breachMinutes} min` }, { label: 'Incident age', value: `${incident.createdMinutesAgo} min` }, { label: 'Evidence status', value: evidenceComplete ? 'Complete' : 'Incomplete' }]; return <section className="incident-summary-strip">{values.map((item) => <div key={item.label}><span>{item.label}</span><strong className={item.critical ? 'temperature-critical' : ''}>{item.value}</strong></div>)}</section>; }

function TemperatureCard({ data }: { data: NonNullable<ReturnType<typeof useInvestigation>['data']> }) { const chartData = data.readings.map((reading) => ({ ...reading, temperatureArea: reading.temperature })); return <section className="investigation-card temperature-evidence-card"><div className="card-heading"><div><span>Last 70 minutes</span><h2>Temperature excursion</h2><p>Calibrated sensor readings aligned to the custody timeline</p></div><ChartLegend items={[{ label: 'Reading', color: '#3478F6', detail: '°C' }, { label: 'Safe range', color: CHART_COLORS.healthy, detail: '2–8°C' }, { label: 'Critical', color: CHART_COLORS.critical, detail: '≥10°C' }]} /></div><div className="temperature-chart" role="img" aria-label="Temperature readings with safe range, warning and critical thresholds"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{ left: -2, right: 22, top: 20, bottom: 8 }}><CartesianGrid stroke="#E5E9EA" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="minute" stroke="#90989F" tick={{ fill: '#6D767E', fontSize: 12 }} tickFormatter={(value: number) => value === 0 ? 'Now' : `${value}m`} /><YAxis stroke="#90989F" tick={{ fill: '#6D767E', fontSize: 12 }} unit="°" domain={[0, 14]} /><Tooltip content={<ChartTooltip units={{ temperature: '°C' }} />} /><ReferenceArea y1={2} y2={8} fill={CHART_COLORS.healthy} fillOpacity={0.1} /><ReferenceArea x1={-45} x2={0} y1={8} y2={14} fill={CHART_COLORS.critical} fillOpacity={0.06} /><ReferenceLine y={8} stroke={CHART_COLORS.warning} strokeDasharray="6 5" label={{ value: 'Warning 8°C', fill: '#A96A1D', fontSize: 12, position: 'insideTopLeft' }} /><ReferenceLine y={10} stroke={CHART_COLORS.critical} strokeDasharray="6 5" label={{ value: 'Critical 10°C', fill: '#B74646', fontSize: 12, position: 'insideTopLeft' }} /><Area dataKey="temperatureArea" tooltipType="none" fill="#3478F6" fillOpacity={0.08} stroke="none" /><Line dataKey="temperature" name="Temperature" stroke="#3478F6" strokeWidth={2.5} dot={(props) => { const point = data.readings[props.index]; return <circle cx={props.cx} cy={props.cy} r={point?.stale || point?.outOfOrder ? 5 : 3.5} fill={point?.stale ? CHART_COLORS.muted : point?.outOfOrder ? CHART_COLORS.warning : '#3478F6'} stroke="#FCFCFB" strokeWidth={2} />; }} /></ComposedChart></ResponsiveContainer></div><div className="temperature-meta"><KeyValue label="Sensor" value={data.incident.sensor} mono /><KeyValue label="Calibration" value="Valid · 12 days ago" /><KeyValue label="Sample interval" value="5 minutes" /><KeyValue label="Reading quality" value="1 stale · 1 out of order" /></div><RouteContext incident={data.incident} /></section>; }

function RouteContext({ incident }: { incident: Incident }) { return <div className="route-context"><div className="route-context-label"><Route size={18} /><span>Custody route</span></div><div className="route-progress-line"><span style={{ width: `${incident.route.progress}%` }} /><i style={{ left: `${incident.route.progress}%` }} /></div><div className="route-stops"><span><strong>{incident.route.from}</strong><small>Released</small></span><span><strong>{incident.route.via}</strong><small>Current custody point</small></span><span><strong>{incident.route.to}</strong><small>Destination</small></span></div></div>; }

function Overview({ incident }: { incident: Incident }) { return <div className="evidence-tab-content overview-detail-grid"><section><span>Breach summary</span><h3><Thermometer size={18} />{(incident.temperature - incident.allowedMax).toFixed(1)}°C above the allowed limit</h3><p>Shipment has remained above its safe temperature for {incident.breachMinutes} minutes.</p></section><dl><div><dt>Sensor health</dt><dd>{incident.sensorHealth}</dd></div><div><dt>Product sensitivity</dt><dd>{incident.productSensitivity}</dd></div><div><dt>Custody verification</dt><dd>4 of 4 checkpoints verified</dd></div><div><dt>Safety rule</dt><dd>Quality hold required</dd></div></dl></div>; }

function SopEvidence({ evidence }: { evidence: NonNullable<ReturnType<typeof useInvestigation>['data']>['evidence'] }) { return <div className="evidence-tab-content"><div className="document-list">{evidence.map((item) => <article key={item.id} className={!item.trusted ? 'untrusted' : ''}><div className="document-icon"><FileCheck2 size={19} /></div><div><div className="document-title"><h3>{item.title}</h3><Badge tone={item.trusted ? 'success' : 'warning'}>{item.trusted ? 'Trusted' : 'Untrusted'}</Badge></div><p>{item.section} · {item.version} · Effective {item.effectiveDate}</p><blockquote>{item.excerpt}</blockquote></div><div className="document-score"><strong>{Math.round(item.score * 100)}%</strong><span>Relevance</span><small className="mono">{item.id}</small></div></article>)}</div></div>; }

function RecommendationPanel({ recommendation }: { recommendation: NonNullable<ReturnType<typeof useInvestigation>['data']>['recommendation'] }) { return <div className="evidence-tab-content recommendation-detail"><div className="advisory-header"><span>Advisory recommendation</span><Badge tone={recommendation.validation === 'valid' ? 'success' : 'critical'}>{recommendation.validation}</Badge></div><h2>{recommendation.action.replaceAll('_', ' ')}</h2><p>{recommendation.rationale}</p><div className="recommendation-facts"><KeyValue label="Evidence sufficient" value={recommendation.evidenceSufficient ? 'Yes' : 'No'} /><KeyValue label="Uncertainty" value={recommendation.uncertainty} /><KeyValue label="Missing information" value={recommendation.missingInformation.join(', ') || 'None identified'} /><KeyValue label="Contraindications" value={recommendation.contraindications.join(', ')} /></div><details className="provenance-details"><summary>Provider and model metadata</summary><div><KeyValue label="Provider / model" value={`${recommendation.provider} · ${recommendation.model}`} /><KeyValue label="Prompt / schema" value={`${recommendation.promptVersion} · ${recommendation.schemaVersion}`} /><KeyValue label="Latency / usage" value={`${recommendation.latencyMs} ms · ${recommendation.tokens} tokens`} /></div></details></div>; }

const governanceGroups: Array<{ title: string; names: string[] }> = [{ title: 'Evidence', names: ['Evidence check', 'Citation check'] }, { title: 'Recommendation validity', names: ['Schema check', 'Provider identity', 'Expiry check'] }, { title: 'Policy', names: ['Policy check', 'Kill-switch state'] }, { title: 'Human authority', names: ['Human approval'] }];
function GovernancePanel({ checks }: { checks: GovernanceCheck[] }) { return <div className="evidence-tab-content governance-groups">{governanceGroups.map((group) => <section key={group.title}><h3>{group.title}</h3>{checks.filter((check) => group.names.includes(check.name)).map((check) => <div className="governance-row" key={check.name}><CheckState state={check.state} /><span><strong>{check.name}</strong><small>{check.detail}</small></span><Badge tone={check.state === 'pass' ? 'success' : check.state === 'warning' ? 'warning' : 'critical'}>{check.state}</Badge></div>)}</section>)}</div>; }

function AuditTimeline({ events, expanded, setExpanded }: { events: AuditEvent[]; expanded: string | null; setExpanded: (id: string | null) => void }) { return <div className="evidence-tab-content audit-timeline spacious">{events.map((event) => <button key={event.id} className="timeline-event" onClick={() => setExpanded(expanded === event.id ? null : event.id)}><span className="timeline-marker" /><time>{formatOffset(event.offsetMinutes)}</time><div><span>{event.type}</span><strong>{event.summary}</strong><small>{event.actor}</small>{expanded === event.id && <dl className="technical-meta"><div><dt>Correlation ID</dt><dd>{event.correlationId}</dd></div><div><dt>Trace ID</dt><dd>{event.traceId}</dd></div></dl>}</div><ChevronDown size={15} /></button>)}</div>; }

function DecisionRail({ incident, persona, recommendation, decided, canDecide, expired, setDecision }: { incident: Incident; persona: string; recommendation: NonNullable<ReturnType<typeof useInvestigation>['data']>['recommendation']; decided: string | null; canDecide: boolean; expired: boolean; setDecision: (decision: Decision) => void }) { return <aside className="human-decision-rail"><div className="decision-rail-header"><span>Human decision</span><div><GovernanceIndicator decision={incident.governance} /><strong><Clock3 size={15} />{expired ? 'Expired' : `${recommendation.expiresInMinutes} min remaining`}</strong></div></div><section className="decision-proposal"><span>Proposed action</span><h2>{recommendation.action.replaceAll('_', ' ')}</h2><p>{recommendation.rationale}</p></section><dl className="decision-details"><div><dt>Operational impact</dt><dd>Shipment isolated at next custody point</dd></div><div><dt>Policy result</dt><dd>Mandatory quality hold</dd></div><div><dt>Evidence completeness</dt><dd>{recommendation.evidenceSufficient ? 'Complete' : 'Incomplete'}</dd></div><div><dt>Reviewer</dt><dd>{persona}</dd></div><div><dt>Shipment</dt><dd className="mono">{incident.shipment}</dd></div></dl><div className="advisory-callout"><LockKeyhole size={18} /><p><strong>The AI recommendation is advisory.</strong>An authorized reviewer makes the final decision.</p></div>{decided && <div className="decision-result"><CheckCircle2 size={18} /><div><strong>{decided}</strong><span>Recorded locally. No real command was sent.</span></div></div>}{!canDecide && <div className="permission-notice"><LockKeyhole size={17} /><span>Your current persona cannot make operational decisions.</span></div>}<div className="decision-controls"><Button variant="primary" disabled={!canDecide || expired} onClick={() => setDecision('approve')}>Approve hold</Button><Button variant="danger" disabled={!canDecide} onClick={() => setDecision('reject')}>Reject</Button><Button variant="ghost" disabled={!canDecide} onClick={() => setDecision('more-info')}>Request information</Button></div><p className="simulated-note">Prototype decision · execution remains simulated</p></aside>; }

const formatOffset = (minutes: number) => minutes === 0 ? 'Now' : `${Math.abs(minutes)}m ago`;
