import { ArrowLeft, ArrowRight, Bot, Check, Database, LockKeyhole, ShieldCheck, UserCheck } from 'lucide-react';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CHART_COLORS, ChartLegend, ChartTooltip } from '../../components/data-display/ChartSupport';
import { KeyValue, Metric, Panel } from '../../components/data-display/Panel';
import { Button, EmptyState } from '../../components/ui/Primitives';
import { GovernanceIndicator } from '../../components/ui/StatusIndicators';
import { dataSourceMode } from '../../data/source';
import { useDashboard, useHealth } from '../../hooks/useControlTower';

const stages = [
  { id: 'evidence', name: 'Evidence', purpose: 'Collect trusted facts and company instructions.', icon: Database, state: 'Ready', plainResult: 'Six sensor readings and two trusted SOP sections were collected.', controls: ['Input validated', 'Evidence snapshot created', 'Timestamps aligned', 'SOP citations retrieved'], output: 'Evidence bundle ready', handoff: 'Validated incident facts and trusted SOP citations pass to the recommendation stage.' },
  { id: 'recommendation', name: 'Recommendation', purpose: 'Create a bounded suggestion from trusted evidence.', icon: Bot, state: 'Ready', plainResult: 'AI recommends holding the shipment for inspection.', controls: ['Action: Hold shipment', 'Evidence: Sufficient', 'Uncertainty: Low', 'Live model call: Disabled in prototype'], output: 'Hold shipment', handoff: 'The structured suggestion passes to fixed safety rules for independent checks.' },
  { id: 'governance', name: 'Governance', purpose: 'Check the suggestion with fixed safety rules.', icon: ShieldCheck, state: 'Approval required', plainResult: 'Safety rules verified the evidence and require human approval.', controls: ['Citations valid', 'Action allowed', 'Recommendation not expired', 'Human approval required'], output: 'Approval required', handoff: 'The verified recommendation and evidence pass to an authorized quality reviewer.' },
  { id: 'human', name: 'Human decision', purpose: 'Keep consequential action with an accountable person.', icon: UserCheck, state: 'Pending', plainResult: 'The shipment cannot be held until an authorized reviewer approves it.', controls: ['Reviewer: Quality reviewer', 'Status: Pending', 'Expires in: 9 minutes'], output: 'Decision pending', handoff: 'No command is created unless the reviewer explicitly approves the shipment hold.' },
] as const;

const trend = [
  { time: '00:00', latency: 720 }, { time: '04:00', latency: 810 }, { time: '08:00', latency: 940 },
  { time: '12:00', latency: 790 }, { time: '16:00', latency: 865 }, { time: '20:00', latency: 742 },
];

const principles = [
  { title: 'AI suggests', detail: 'The model reviews the incident and company instructions.', icon: Bot },
  { title: 'Rules verify', detail: 'Fixed safety rules check the evidence, citations and proposed action.', icon: ShieldCheck },
  { title: 'A human decides', detail: 'An authorized reviewer approves or rejects consequential actions.', icon: UserCheck },
] as const;

export function GovernedAI() {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const navigate = useNavigate();
  const { data: dashboard } = useDashboard();
  const { data: health } = useHealth();
  const selected = stages[selectedIndex]!;
  const selectStage = (index: number) => setSelectedIndex(Math.max(0, Math.min(stages.length - 1, index)));

  if (dataSourceMode === 'api') {
    const incident = dashboard?.incidents[0];
    return <div className="page governance-page governance-polished">
      <section className="governance-intro"><div><span className="section-kicker">Governed recommendations</span><h1>Governed AI</h1><h2>The model recommends. Policy governs. Humans authorize.</h2><p>Opening this view never initiates a provider request.</p></div><div className="execution-mode" aria-label="Execution mode"><KeyValue label="Provider" value={health?.provider ?? 'Unavailable'} /><KeyValue label="Model" value={health?.model || 'Not configured'} /><KeyValue label="Configured" value={health ? health.providerConfigured ? 'Yes' : 'No' : 'Unavailable'} /><KeyValue label="Live calls" value={health ? health.liveCallsEnabled ? 'Enabled' : 'Disabled' : 'Unavailable'} /><KeyValue label="Fallback" value={health ? health.fallbackAvailable ? 'Available' : 'Unavailable' : 'Unavailable'} /></div></section>
      <section className="governance-story" aria-labelledby="governance-story-title"><header><span className="section-kicker">Three control layers</span><h2 id="governance-story-title">How a recommendation becomes a safe action</h2></header><div>{principles.map(({ title, detail, icon: Icon }, index) => <article key={title}><span>{index + 1}</span><Icon size={20} aria-hidden="true" /><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div></section>
      {!incident ? <section><EmptyState title="No recommendation lifecycle yet" detail="Run a sustained-breach scenario in Demo Lab to create an authoritative incident." /><Button variant="primary" onClick={() => void navigate('/demo-lab')}>Open Demo Lab</Button></section> : <section className="current-example"><div><span className="section-kicker">Most recent incident</span><h2><span className="mono">{incident.id}</span></h2><p>{incident.title}</p></div><dl><div><dt>Shipment</dt><dd className="mono">{incident.shipment}</dd></div><div><dt>Governance</dt><dd><GovernanceIndicator decision={incident.governance} /></dd></div><div><dt>State</dt><dd>{incident.state}</dd></div><div><dt>Temperature</dt><dd>{incident.temperature === null ? 'Unavailable' : `${incident.temperature.toFixed(1)}°C`}</dd></div></dl><Button variant="primary" onClick={() => void navigate(`/investigation/${incident.id}`)}>Open incident investigation <ArrowRight size={16} /></Button></section>}
      <Panel title="Recent governed decisions" eyebrow="Authoritative incident records"><div className="outcome-table governed-activity">{dashboard?.recommendations.length ? dashboard.recommendations.map((item) => <div key={`${item.incident}-${item.time}`}><span className="mono">{item.incident}</span><strong>{item.action.replaceAll('_', ' ')}</strong><span>{item.outcome}</span><time>{item.time}</time></div>) : <p>No governed decisions reported.</p>}</div></Panel>
    </div>;
  }

  return <div className="page governance-page governance-polished">
    <section className="governance-intro"><div><span className="section-kicker">Governed recommendations</span><h1>Governed AI</h1><h2>The model recommends. Policy governs. Humans authorize.</h2><p>Every recommendation must pass evidence, validation and policy controls before a human can authorize an operational action.</p></div><div className="execution-mode" aria-label="Execution mode"><KeyValue label="Provider" value="Groq" /><KeyValue label="Live calls" value="Disabled" /><KeyValue label="Mode" value="Deterministic prototype" /><KeyValue label="Fallback" value="Available" /></div></section>

    <section className="governance-story" aria-labelledby="governance-story-title"><header><span className="section-kicker">Three control layers</span><h2 id="governance-story-title">How a recommendation becomes a safe action</h2></header><div>{principles.map(({ title, detail, icon: Icon }, index) => <article key={title}><span>{index + 1}</span><Icon size={20} aria-hidden="true" /><div><h3>{title}</h3><p>{detail}</p></div></article>)}</div><strong>The model recommends. Policy governs. Humans authorize.</strong></section>

    <section className="current-example" aria-labelledby="current-example-title"><div><span className="section-kicker">Live walkthrough</span><h2 id="current-example-title">Current example · <span className="mono">INC-2481</span></h2><p>Shipment has remained above its safe temperature for 47 minutes.</p></div><dl><div><dt>Shipment</dt><dd>Vaccine shipment · <span className="mono">CCS-CHI-1842</span></dd></div><div><dt>Route</dt><dd>Chicago → Denver</dd></div><div><dt>Current</dt><dd>11.8°C</dd></div><div><dt>Safe range</dt><dd>2–8°C</dd></div><div><dt>Unsafe for</dt><dd>47 minutes</dd></div><div><dt>Status</dt><dd><GovernanceIndicator decision="approval-required" /></dd></div></dl><div className="example-progress" aria-label={`Stage ${selectedIndex + 1} of ${stages.length}: ${selected.name}`}>{stages.map((stage, index) => <span className={index < selectedIndex ? 'complete' : index === selectedIndex ? 'current' : ''} key={stage.id}><i>{index < selectedIndex ? <Check size={13} /> : index + 1}</i>{stage.name}</span>)}</div></section>

    <section className="lifecycle-card"><header><div><span>Control boundary</span><h2>Recommendation lifecycle</h2></div><small>Four governed handoffs</small></header><div className="lifecycle-stepper" role="tablist" aria-label="Governed recommendation lifecycle">{stages.map((stage, index) => { const Icon = stage.icon; const selectedStage = index === selectedIndex; return <button role="tab" aria-selected={selectedStage} aria-controls="stage-workspace" id={`stage-${stage.id}`} className={selectedStage ? 'selected' : ''} key={stage.id} onClick={() => selectStage(index)}><span className="step-marker">{index + 1}</span><Icon size={18} aria-hidden="true" /><span><strong>{stage.name}</strong><small>{stage.purpose}</small></span><em>{stage.state}</em></button>; })}</div><div id="stage-workspace" role="tabpanel" aria-labelledby={`stage-${selected.id}`} className="stage-workspace"><section><span>Plain-language result</span><h3>{selected.plainResult}</h3><div className="technical-controls"><span>Technical controls</span><ul>{selected.controls.map((control) => <li key={control}><Check size={15} aria-hidden="true" />{control}</li>)}</ul></div></section><aside><span>Passed to the next stage</span><strong>{selected.output}</strong><p>{selected.handoff}</p>{selected.id === 'governance' ? <GovernanceIndicator decision="approval-required" /> : selected.id === 'human' ? <GovernanceIndicator decision="pending" /> : <div className="stage-ready"><Check size={15} />Ready for next stage</div>}</aside><footer className="stage-navigation"><Button variant="secondary" onClick={() => selectStage(selectedIndex - 1)} disabled={selectedIndex === 0}><ArrowLeft size={15} />Previous</Button><span>Stage {selectedIndex + 1} of {stages.length}</span><Button variant="primary" onClick={() => selectStage(selectedIndex + 1)} disabled={selectedIndex === stages.length - 1}>Next stage <ArrowRight size={15} /></Button></footer></div></section>

    <section className="governance-outcome"><div><span className="section-kicker">What happens next?</span><h2>A human decision protects the shipment</h2><p>A quality reviewer must inspect the evidence and approve or reject the shipment hold.</p></div><Button variant="primary" onClick={() => void navigate('/investigation/INC-2481')}>Open incident investigation <ArrowRight size={16} /></Button></section>

    <div className="summary-strip primary-metrics governance-metrics"><Metric label="Validation pass rate" value="98.6%" detail="Schema and citation checks" tone="success" /><Metric label="Deterministic fallback" value="3.2%" detail="Below 5% objective" /><Metric label="Evidence sufficient" value="91.3%" detail="Recent recommendations" /><Metric label="Awaiting review" value="2" detail="No automatic execution" tone="warning" /></div>

    <div className="governance-content-grid polished"><Panel title="Recommendation performance" eyebrow="P95 latency · last 24 hours" className="performance-panel"><ChartLegend items={[{ label: 'Recommendation latency', color: CHART_COLORS.primary, detail: 'milliseconds' }]} /><div className="chart-wrap governance-chart" role="img" aria-label="Recommendation latency over 24 hours"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ left: -2, right: 15, top: 10, bottom: 4 }}><CartesianGrid stroke="#E5E9EA" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="time" tick={{ fill: '#6D767E', fontSize: 12 }} /><YAxis tick={{ fill: '#6D767E', fontSize: 12 }} unit="ms" /><Tooltip content={<ChartTooltip units={{ latency: ' ms' }} />} /><Area dataKey="latency" name="Recommendation latency" stroke={CHART_COLORS.primary} fill={CHART_COLORS.primary} fillOpacity={0.09} strokeWidth={2.5} /></AreaChart></ResponsiveContainer></div></Panel><Panel title="Recent governed decisions" eyebrow="Operational activity" className="recent-outcomes"><div className="outcome-table governed-activity"><div className="outcome-head"><span>Incident</span><span>Action</span><span>Result</span><span>Age</span></div><div><span className="mono">INC-2481</span><strong>Hold shipment</strong><span><GovernanceIndicator decision="approval-required" /><small>Waiting for human approval</small></span><time>2 minutes ago</time></div><div><span className="mono">INC-2480</span><strong>Continue monitoring</strong><span><GovernanceIndicator decision="allowed" /><small>Allowed by policy</small></span><time>29 minutes ago</time></div><div><span className="mono">INC-2478</span><strong>Request inspection</strong><span><GovernanceIndicator decision="fallback" /><small>Deterministic fallback used</small></span><time>1 hour ago</time></div></div></Panel></div>

    <details className="governance-provenance"><summary><LockKeyhole size={16} />Provenance and configuration</summary><div><KeyValue label="Provider / model" value="Groq · openai/gpt-oss-20b" /><KeyValue label="Prompt / schema" value="recommendation.v1 · 1.0.0 strict" /><KeyValue label="Retrieval collection" value="coldchain-sop-v1" mono /><p>Provider identity is fixture metadata. This prototype never contacts an external model.</p></div></details>
  </div>;
}
