import { ArrowRight, Clock3, MapPin, PackageCheck, ShieldAlert, ThermometerSun } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CHART_COLORS, ChartLegend, ChartTooltip } from '../../components/data-display/ChartSupport';
import { Button } from '../../components/ui/Primitives';
import { GovernanceIndicator, SeverityIndicator, WorkflowIndicator } from '../../components/ui/StatusIndicators';
import type { Incident, LiveTelemetryRow } from '../../data/contracts';
import { liveTelemetry } from '../../data/fixtures';
import { deriveIncidentSummary } from '../../data/selectors/incidents';
import { useDashboard } from '../../hooks/useControlTower';

const resolved = [4, 6, 5, 8, 7, 10, 9];

export function CommandCenter() {
  const { data, isLoading } = useDashboard();
  const navigate = useNavigate();
  const [range, setRange] = useState<'Daily' | 'Weekly' | 'Monthly'>('Daily');
  const chartData = useMemo(() => data?.trend.map((point, index) => ({ ...point, warning: Math.max(point.incidents - point.breaches, 0), critical: point.breaches, resolved: resolved[index] })) ?? [], [data]);
  if (isLoading || !data) return <DashboardSkeleton />;
  const openIncidents = data.incidents.filter((incident) => incident.state !== 'completed').length;
  const incidentSummary = deriveIncidentSummary(data.incidents);
  const urgent = data.incidents.find((incident) => incident.severity === 'critical') ?? data.incidents[0]!;

  return <div className="page command-center light-command-center">
    <section className="operations-summary">
      <div className="summary-content">
        <div className="summary-heading"><div><span className="section-kicker">Operations overview</span><h1>Cold-chain operations</h1><p>Temperature integrity, governed decisions and shipment risk</p></div><span className="updated-time">Updated just now</span></div>
        <div className="summary-metrics"><SummaryMetric label="Shipments monitored" value="128" detail="Across 14 active routes" /><SummaryMetric label="Open incidents" value={openIncidents} detail={`${incidentSummary.criticalCount} require urgent attention`} tone="critical" /><SummaryMetric label="Awaiting review" value={incidentSummary.approvalQueueCount} detail="Human authorization required" tone="warning" /></div>
        <div className="shipment-distribution" aria-label="Shipment status distribution"><div className="distribution-bar"><span className="distribution-healthy" style={{ width: '82%' }} /><span className="distribution-risk" style={{ width: '12%' }} /><span className="distribution-critical" style={{ width: '6%' }} /></div><div className="distribution-legend"><span><i className="dot-healthy" />Healthy <strong>105</strong></span><span><i className="dot-warning" />At risk <strong>15</strong></span><span><i className="dot-critical" />Critical <strong>8</strong></span></div></div>
      </div>
      <LiveTelemetry rows={liveTelemetry} />
    </section>

    <section className="dashboard-main-grid">
      <div className="attention-stack"><AttentionCard title="Critical incidents" value={incidentSummary.criticalCount} detail={`${incidentSummary.sustainedBreachCount} sustained · ${incidentSummary.immediateBreachCount} immediate`} trend="1 new since 08:00" tone="critical" points="4,29 24,25 44,26 64,17 84,20 104,8" /><AttentionCard title="Approval queue" value={incidentSummary.approvalQueueCount} detail={`Oldest waiting ${incidentSummary.oldestWaitingMinutes} min`} trend="1 expires in 9 min" tone="warning" points="4,27 24,25 44,20 64,22 84,14 104,15" /></div>
      <section className="dashboard-card shipment-health-card"><div className="card-heading"><div><span>Current network</span><h2>Shipment health</h2></div><PackageCheck size={20} /></div><div className="health-total"><strong>128</strong><span>monitored shipments</span></div><div className="health-list"><HealthRow label="Healthy" count={105} percent={82} tone="healthy" /><HealthRow label="At risk" count={15} percent={12} tone="warning" /><HealthRow label="Critical" count={8} percent={6} tone="critical" /><HealthRow label="Unknown" count={0} percent={0} tone="muted" /></div></section>
      <section className="dashboard-card incident-activity-card"><div className="card-heading"><div><span>Operational events</span><h2>Incident activity</h2></div><div className="range-selector" aria-label="Incident activity range">{(['Daily', 'Weekly', 'Monthly'] as const).map((item) => <button className={range === item ? 'active' : ''} key={item} onClick={() => setRange(item)}>{item}</button>)}</div></div><ChartLegend items={[{ label: 'Warning', color: CHART_COLORS.warning }, { label: 'Critical', color: CHART_COLORS.critical }, { label: 'Resolved', color: CHART_COLORS.healthy }]} /><div className="activity-chart" role="img" aria-label={`${range} warning, critical, and resolved incident activity`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ left: -8, right: 14, top: 10, bottom: 2 }}><defs><linearGradient id="resolvedFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={CHART_COLORS.healthy} stopOpacity={0.16} /><stop offset="100%" stopColor={CHART_COLORS.healthy} stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#E5E9EA" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="hour" stroke="#90989F" tick={{ fill: '#6D767E', fontSize: 12 }} /><YAxis stroke="#90989F" tick={{ fill: '#6D767E', fontSize: 12 }} allowDecimals={false} /><Tooltip content={<ChartTooltip units={{ warning: ' incidents', critical: ' incidents', resolved: ' incidents' }} />} /><Area type="monotone" dataKey="resolved" name="Resolved" stroke={CHART_COLORS.healthy} fill="url(#resolvedFill)" strokeWidth={2.25} /><Line type="monotone" dataKey="warning" name="Warning" stroke={CHART_COLORS.warning} strokeWidth={2.25} dot={{ r: 3 }} /><Line type="monotone" dataKey="critical" name="Critical" stroke={CHART_COLORS.critical} strokeWidth={2.25} dot={{ r: 3 }} /></AreaChart></ResponsiveContainer></div></section>
    </section>

    <section className="dashboard-bottom-grid">
      <section className="dashboard-card priority-table-card"><div className="card-heading"><div><span>Requires attention</span><h2>Priority incidents</h2></div><button className="card-link" onClick={() => void navigate('/incidents')}>View all incidents <ArrowRight size={15} /></button></div><PriorityTable incidents={data.incidents.slice(0, 5)} onOpen={(id) => void navigate(`/investigation/${id}`)} /></section>
      <UrgentShipment incident={urgent} onInvestigate={() => void navigate(`/investigation/${urgent.id}`)} />
    </section>
  </div>;
}

function SummaryMetric({ label, value, detail, tone = 'neutral' }: { label: string; value: string | number; detail: string; tone?: 'neutral' | 'critical' | 'warning' }) { return <div className={`summary-metric tone-${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }

function LiveTelemetry({ rows }: { rows: LiveTelemetryRow[] }) { return <section className="live-telemetry" aria-label="Live telemetry"><header><div><span>Streaming now</span><h2>Live telemetry</h2></div><small>Latest calibrated readings</small></header><div>{rows.map((row) => <article key={row.id}><div className="telemetry-identity"><strong>{row.route}</strong><span>{row.product} · <span className="mono">{row.id}</span></span></div><div className="telemetry-reading"><strong>{row.temperature.toFixed(1)}°C</strong><span>{row.allowedMin}–{row.allowedMax}°C</span></div><SeverityIndicator severity={row.state} /><Sparkline values={row.trend} tone={row.state} /><time>{row.lastReading}</time></article>)}</div></section>; }

function Sparkline({ values, tone }: { values: number[]; tone: Incident['severity'] }) { const min = Math.min(...values); const max = Math.max(...values); const range = max - min || 1; const points = values.map((value, index) => `${4 + index * 18},${28 - ((value - min) / range) * 22}`).join(' '); return <svg className={`telemetry-sparkline sparkline-${tone}`} viewBox="0 0 98 32" aria-hidden="true"><polyline points={points} /></svg>; }

function AttentionCard({ title, value, detail, trend, tone, points }: { title: string; value: number; detail: string; trend: string; tone: 'critical' | 'warning'; points: string }) { return <article className={`dashboard-card attention-card attention-${tone}`}><div><span>{title}</span><strong>{value}</strong><p>{detail}</p><small>{trend}</small></div><svg viewBox="0 0 108 36" aria-label={`${title} trend`}><polyline points={points} /><line x1="4" x2="104" y1="32" y2="32" /></svg></article>; }

function HealthRow({ label, count, percent, tone }: { label: string; count: number; percent: number; tone: string }) { return <div className="health-row"><div><span className={`health-dot health-${tone}`} />{label}</div><strong>{count}</strong><div className="health-track"><span className={`health-${tone}`} style={{ width: `${percent}%` }} /></div><small>{percent}%</small></div>; }

function PriorityTable({ incidents, onOpen }: { incidents: Incident[]; onOpen: (id: string) => void }) { return <div className="priority-table" role="table" aria-label="Priority incidents"><div className="priority-table-head" role="row"><span role="columnheader">Incident</span><span role="columnheader">Shipment</span><span role="columnheader">Product</span><span role="columnheader">Temperature</span><span role="columnheader">Severity</span><span role="columnheader">State</span><span role="columnheader">Age</span><span role="columnheader">Reviewer</span></div>{incidents.map((incident, index) => <div key={incident.id} role="row" tabIndex={0} aria-label={`Open ${incident.id}`} className={`priority-table-row ${index === 0 ? 'selected' : ''}`} onClick={() => onOpen(incident.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onOpen(incident.id); } }}><span role="cell"><strong>{incident.title}</strong><small className="mono">{incident.id}</small><small className="priority-reviewer-secondary">Reviewer: {incident.reviewer ?? 'Unassigned'}</small></span><span role="cell" className="mono">{incident.shipment}</span><span role="cell">{incident.product}</span><span role="cell" className={incident.severity === 'critical' ? 'temperature-critical' : ''}>{incident.temperature.toFixed(1)}°C<small>{incident.allowedMin}–{incident.allowedMax}°C</small></span><span role="cell" className="priority-severity-cell"><SeverityIndicator severity={incident.severity} /></span><span role="cell" className="priority-state-cell"><WorkflowIndicator state={incident.state} /></span><span role="cell" className="priority-age-cell" aria-label={`Age: ${incident.createdMinutesAgo} minutes`}>{incident.createdMinutesAgo}m</span><span role="cell" className="priority-reviewer-cell">{incident.reviewer ?? 'Unassigned'}</span></div>)}</div>; }

function UrgentShipment({ incident, onInvestigate }: { incident: Incident; onInvestigate: () => void }) { return <section className="dashboard-card urgent-shipment"><div className="card-heading"><div><span>Highest priority</span><h2>Most urgent shipment</h2></div><ShieldAlert size={20} /></div><div className="urgent-title"><div><strong className="mono">{incident.shipment}</strong><span>{incident.product}</span></div><SeverityIndicator severity={incident.severity} /></div><div className="urgent-route"><MapPin size={17} /><span>{incident.route.from}</span><i /><span>{incident.route.via}</span><i /><span>{incident.route.to}</span></div><div className="urgent-readings"><div><ThermometerSun size={18} /><span>Current<strong>{incident.temperature.toFixed(1)}°C</strong></span></div><div><span>Allowed<strong>{incident.allowedMin}–{incident.allowedMax}°C</strong></span></div><div><Clock3 size={18} /><span>Breach<strong>{incident.breachMinutes} min</strong></span></div></div><div className="custody-progress"><div><span>Custody progress</span><strong>{incident.route.progress}%</strong></div><div><span style={{ width: `${incident.route.progress}%` }} /></div></div><div className="urgent-governance"><GovernanceIndicator decision={incident.governance} /><span>Deterministic policy recommends a quality hold.</span></div><Button variant="primary" onClick={onInvestigate}>Investigate <ArrowRight size={16} /></Button></section>; }

function DashboardSkeleton() { return <div className="page"><div className="skeleton skeleton-panel tall" /></div>; }
